# Generated by Django 5.1 on 2024-08-23 21:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('address', models.CharField(default='', max_length=150)),
                ('cpf', models.CharField(default='', max_length=14)),
                ('phone', models.CharField(default='', max_length=15)),
                ('email', models.EmailField(default='', max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('wage', models.FloatField(default=0.0)),
                ('sales_count', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
                ('description', models.CharField(default='', max_length=255)),
                ('price', models.FloatField(default=0.0)),
                ('quantity_in_stock', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Shopping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_value', models.FloatField(default=0.0)),
                ('id_client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fla_loja.client')),
            ],
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(verbose_name='Date purchased')),
                ('id_employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fla_loja.employee')),
                ('id_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fla_loja.product')),
                ('id_shopping', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fla_loja.shopping')),
            ],
        ),
    ]
