# Generated by Django 5.1 on 2024-08-24 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fla_loja', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='photo',
            field=models.ImageField(default='', upload_to=None),
        ),
        migrations.AddField(
            model_name='employee',
            name='photo',
            field=models.ImageField(default='', upload_to=None),
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default='', upload_to=None),
        ),
    ]
