# Generated by Django 5.1 on 2024-08-24 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fla_loja', '0002_client_photo_employee_photo_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
