# Generated by Django 5.1 on 2024-08-25 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fla_loja', '0003_sale_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='photo',
            field=models.ImageField(default='flamengo/fla_loja/static/empoyees', upload_to=None),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='flamengo/fla_loja/static/products', upload_to=None),
        ),
    ]
