# Generated by Django 5.1 on 2024-08-25 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fla_loja', '0004_alter_employee_photo_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='photo',
            field=models.ImageField(default='', upload_to='flamengo/fla_loja/static/empoyees'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='', upload_to='flamengo/fla_loja/static/products'),
        ),
    ]
