# Generated by Django 5.1 on 2024-08-26 01:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fla_loja', '0004_alter_sale_data'),
        ('fla_loja', '0010_alter_employee_photo_alter_product_image'),
    ]

    operations = [
    ]
