# Generated by Django 5.1 on 2024-08-26 01:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fla_loja', '0011_merge_20240826_0111'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='id_shopping',
        ),
        migrations.RemoveField(
            model_name='client',
            name='photo',
        ),
        migrations.AddField(
            model_name='sale',
            name='id_client',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, to='fla_loja.client'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='id_employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='fla_loja.employee'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='id_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='fla_loja.product'),
        ),
        migrations.DeleteModel(
            name='Shopping',
        ),
    ]
