# Generated by Django 5.1 on 2024-08-26 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fla_loja', '0013_alter_sale_id_client_alter_sale_id_employee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='activate',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='activate',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='product',
            name='activate',
            field=models.BooleanField(default=True),
        ),
    ]
