# Generated by Django 5.1 on 2024-10-15 17:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fla_loja', '0015_remove_client_activate_remove_employee_activate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='data',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='id_client',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='id_employee',
        ),
        migrations.AddField(
            model_name='client',
            name='password',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='employee',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AddField(
            model_name='employee',
            name='password',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(verbose_name='Date purchased')),
                ('payment_method', models.CharField(default='', max_length=20)),
                ('status', models.CharField(default='', max_length=30)),
                ('id_client', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='fla_loja.client')),
                ('id_employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='fla_loja.employee')),
            ],
        ),
        migrations.AddField(
            model_name='sale',
            name='id_car',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='fla_loja.car'),
        ),
    ]
