# Generated by Django 5.1 on 2024-10-15 18:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fla_loja', '0016_remove_sale_data_remove_sale_id_client_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Sale',
            new_name='PurchasesCompleted',
        ),
        migrations.CreateModel(
            name='PurchasesNotCompleted',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('id_car', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='fla_loja.car')),
                ('id_product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='fla_loja.product')),
            ],
        ),
    ]
