# Generated by Django 5.1 on 2024-10-17 20:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fla_loja', '0018_product_category_product_made_in_alter_client_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='data',
            new_name='date',
        ),
        migrations.AlterField(
            model_name='car',
            name='id_employee',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='fla_loja.employee'),
        ),
        migrations.AlterField(
            model_name='car',
            name='status',
            field=models.CharField(default='Não finalizado', max_length=30),
        ),
    ]
