# Generated by Django 5.1 on 2024-10-20 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fla_loja', '0020_alter_employee_sales_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='cupomPercent',
            field=models.FloatField(default=0.0),
        ),
    ]
