# Generated by Django 5.1 on 2024-10-20 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fla_loja', '0020_alter_employee_sales_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='cupomPercent',
            field=models.FloatField(default=0.0),
        ),
        
        migrations.RunSQL(
            sql="""
                CREATE PROCEDURE get_low_stock_products(
                    IN threshold INT
                )
                BEGIN
                    SELECT *
                    FROM Product
                    WHERE quantity_in_stock < threshold;
                END;
            """,
            reverse_sql="DROP PROCEDURE IF EXISTS get_low_stock_products;"
        ),
    ]
